// URL templates adapted from Referencias/infoooze/src/userRecon.js
// We intentionally keep this as a status-only list for fast probing.
export const INFOOOZE_URLS: string[] = [
  // Redes Sociais Principais
  'https://facebook.com/{username}',
  'https://instagram.com/{username}',
  'https://twitter.com/{username}',
  'https://x.com/{username}',
  'https://youtube.com/{username}',
  'https://tiktok.com/@{username}',
  'https://linkedin.com/in/{username}',
  'https://snapchat.com/add/{username}',
  'https://discord.com/users/{username}',
  'https://telegram.me/{username}',
  'https://whatsapp.com/{username}',
  'https://signal.me/#p/{username}',
  
  // Plataformas de Vídeo
  'https://vimeo.com/{username}',
  'https://twitch.tv/{username}',
  'https://kick.com/{username}',
  'https://rumble.com/user/{username}',
  'https://bitchute.com/profile/{username}',
  'https://odysee.com/@{username}',
  'https://www.dailymotion.com/{username}',
  'https://d.tube/#!/c/{username}',
  
  // Desenvolvimento e Tech
  'https://github.com/{username}',
  'https://gitlab.com/{username}',
  'https://bitbucket.org/{username}',
  'https://stackoverflow.com/users/{username}',
  'https://stackexchange.com/users/{username}',
  'https://codepen.io/{username}',
  'https://codesandbox.io/u/{username}',
  'https://repl.it/@{username}',
  'https://glitch.com/@{username}',
  'https://npmjs.com/~{username}',
  'https://pypi.org/user/{username}',
  'https://packagist.org/users/{username}',
  'https://rubygems.org/profiles/{username}',
  'https://hub.docker.com/u/{username}',
  'https://launchpad.net/~{username}',
  'https://sourceforge.net/u/{username}',
  'https://keybase.io/{username}',
  'https://hackerone.com/{username}',
  'https://bugcrowd.com/{username}',
  'https://leetcode.com/{username}',
  'https://hackerrank.com/{username}',
  'https://codewars.com/users/{username}',
  'https://codeforces.com/profile/{username}',
  'https://atcoder.jp/users/{username}',
  'https://topcoder.com/members/{username}',
  'https://kaggle.com/{username}',
  'https://huggingface.co/{username}',
  'https://observablehq.com/@{username}',
  'https://www.codecademy.com/{username}',
  'https://www.codementor.io/{username}',
  'https://dev.to/{username}',
  'https://hashnode.com/@{username}',
  
  // Plataformas de Blog/Escrita
  'https://medium.com/@{username}',
  'https://substack.com/@{username}',
  'https://ghost.org/{username}',
  'https://write.as/{username}',
  'https://telegra.ph/{username}',
  'https://{username}.blogspot.com/',
  'https://{username}.tumblr.com/',
  'https://{username}.wordpress.com/',
  'https://{username}.livejournal.com/',
  'https://{username}.hubpages.com',
  'https://{username}.contently.com',
  'https://www.scribd.com/{username}',
  'https://www.wattpad.com/user/{username}',
  'https://www.goodreads.com/{username}',
  'https://www.quotev.com/{username}',
  
  // Design e Arte
  'https://dribbble.com/{username}',
  'https://behance.net/{username}',
  'https://www.artstation.com/{username}',
  'https://{username}.deviantart.com/',
  'https://{username}.devianart.com/',
  'https://www.pinterest.com/{username}',
  'https://unsplash.com/@{username}',
  'https://500px.com/p/{username}',
  'https://flickr.com/people/{username}',
  'https://imgur.com/user/{username}',
  'https://www.shutterstock.com/g/{username}',
  'https://www.adobe.com/creativecloud/{username}',
  'https://www.canva.com/{username}',
  'https://www.figma.com/@{username}',
  'https://www.designspiration.net/{username}',
  'https://www.colourlovers.com/love/{username}',
  'https://creativemarket.com/{username}',
  'https://ello.co/{username}',
  'https://vsco.co/{username}',
  
  // Música e Audio
  'https://soundcloud.com/{username}',
  'https://mixcloud.com/{username}',
  'https://open.spotify.com/user/{username}',
  'https://music.apple.com/profile/{username}',
  'https://www.last.fm/user/{username}',
  'https://www.bandcamp.com/{username}',
  'https://www.reverbnation.com/{username}',
  'https://audiomack.com/{username}',
  'https://www.shazam.com/user/{username}',
  'https://blip.fm/{username}',
  'https://www.deezer.com/en/profile/{username}',
  'https://tidal.com/browse/user/{username}',
  'https://www.pandora.com/people/{username}',
  
  // Jogos
  'https://steamcommunity.com/id/{username}',
  'https://www.twitch.tv/{username}',
  'https://www.roblox.com/users/{username}',
  'https://fortnitetracker.com/profile/all/{username}',
  'https://www.minecraft.net/en-us/profile/{username}',
  'https://www.chess.com/member/{username}',
  'https://lichess.org/@/{username}',
  'https://www.kongregate.com/accounts/{username}',
  'https://www.newgrounds.com/{username}',
  'https://itch.io/profile/{username}',
  'https://www.epicgames.com/site/en-US/user/{username}',
  'https://www.origin.com/user/{username}',
  'https://www.ubisoft.com/en-us/player/{username}',
  'https://www.battlenet.com/{username}',
  'https://www.playstation.com/en-us/my/profile/{username}',
  'https://www.xbox.com/en-US/Profile?Gamertag={username}',
  'https://www.nintendo.com/us/profile/{username}',
  
  // Profissional e Negócios
  'https://about.me/{username}',
  'https://angel.co/{username}',
  'https://www.crunchbase.com/person/{username}',
  'https://www.freelancer.com/u/{username}',
  'https://www.upwork.com/freelancers/{username}',
  'https://www.fiverr.com/{username}',
  'https://www.guru.com/{username}',
  'https://99designs.com/profiles/{username}',
  'https://www.peopleperhour.com/freelancer/{username}',
  'https://www.toptal.com/freelance/{username}',
  'https://www.xing.com/profile/{username}',
  'https://viadeo.journaldunet.com/p/{username}',
  
  // E-commerce e Marketplace
  'https://www.etsy.com/shop/{username}',
  'https://www.ebay.com/usr/{username}',
  'https://www.amazon.com/sp?seller={username}',
  'https://www.gumroad.com/{username}',
  'https://www.patreon.com/{username}',
  'https://ko-fi.com/{username}',
  'https://buymeacoffee.com/{username}',
  'https://www.paypal.me/{username}',
  'https://cash.app/${username}',
  'https://venmo.com/{username}',
  'https://www.mercadolibre.com.ar/{username}',
  'https://produto.mercadolivre.com.br/{username}',
  'https://www.olx.com.br/usuario/{username}',
  
  // Conhecimento e Educação
  'https://www.wikipedia.org/wiki/User:{username}',
  'https://www.quora.com/profile/{username}',
  'https://www.reddit.com/user/{username}',
  'http://old.reddit.com/user/{username}',
  'https://www.coursera.org/user/{username}',
  'https://www.udemy.com/user/{username}',
  'https://www.khanacademy.org/profile/{username}',
  'https://www.edx.org/profile/{username}',
  'https://www.skillshare.com/user/{username}',
  'https://www.lynda.com/members/{username}',
  'https://www.pluralsight.com/profile/{username}',
  'https://www.instructables.com/member/{username}',
  'https://www.academia.edu/{username}',
  'https://www.researchgate.net/profile/{username}',
  'https://scholar.google.com/citations?user={username}',
  'https://orcid.org/{username}',
  
  // Plataformas Brasileiras
  'https://www.orkut.com.br/Profile?uid={username}',
  'https://www.kwai.com/@{username}',
  'https://www.olx.com.br/perfil/{username}',
  'https://www.enjoei.com.br/{username}',
  'https://www.vinted.com.br/member/{username}',
  'https://www.99freelas.com.br/user/{username}',
  'https://www.workana.com/freelancer/{username}',
  'https://www.getninjas.com.br/user/{username}',
  'https://www.clubhouse.com/@{username}',
  
  // Redes Sociais Regionais/Alternativas
  'https://vk.com/{username}',
  'https://ok.ru/{username}',
  'https://weibo.com/{username}',
  'https://www.qq.com/{username}',
  'https://line.me/ti/p/{username}',
  'https://www.wechat.com/{username}',
  'https://www.kakaotalk.com/{username}',
  'https://mastodon.social/@{username}',
  'https://diasp.org/people/{username}',
  'https://www.minds.com/{username}',
  'https://gab.com/{username}',
  'https://parler.com/profile/{username}',
  'https://gettr.com/user/{username}',
  'https://truthsocial.com/@{username}',
  'https://www.mewe.com/{username}',
  'https://www.vero.co/{username}',
  'https://www.badoo.com/en/{username}',
  'https://www.meetup.com/members/{username}',
  'https://www.bumble.com/{username}',
  'https://www.hinge.co/{username}',
  'https://www.okcupid.com/profile/{username}',
  'https://www.match.com/{username}',
  'https://www.pof.com/viewprofile.aspx?profile_id={username}',
  'https://www.zoosk.com/profile/{username}',
  
  // Viagens e Localização
  'https://www.tripadvisor.com/members/{username}',
  'https://www.airbnb.com/users/show/{username}',
  'https://www.couchsurfing.com/people/{username}',
  'https://www.hostelworld.com/user/{username}',
  'https://www.booking.com/profile/{username}',
  'https://foursquare.com/{username}',
  'https://www.swarmapp.com/user/{username}',
  'https://untappd.com/user/{username}',
  'https://www.yelp.com/user_details?userid={username}',
  'https://www.zomato.com/{username}',
  'https://www.trip.skyscanner.com/user/{username}',
  
  // Fóruns e Comunidades
  'https://disqus.com/{username}',
  'https://www.discourse.org/u/{username}',
  'https://forum.xda-developers.com/member.php?username={username}',
  'https://www.phpbb.com/community/memberlist.php?mode=viewprofile&u={username}',
  'https://mybb.com/member.php?action=profile&uid={username}',
  'https://www.vbulletin.com/forum/member.php/{username}',
  'https://www.invisioncommunity.com/profile/{username}',
  'https://8kun.top/{username}',
  'https://voat.co/user/{username}',
  
  // Cyber Security e Hacking
  'http://www.zone-h.org/archive/notifier={username}',
  'https://www.exploit-db.com/author/{username}',
  'https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword={username}',
  'https://www.rapid7.com/db/?type=nexpose&q={username}',
  'https://www.shodan.io/user/{username}',
  'https://censys.io/certificates?q={username}',
  'https://www.virustotal.com/gui/user/{username}',
  'https://www.hybrid-analysis.com/user/{username}',
  'https://www.malshare.com/user.php?user={username}',
  'https://bazaar.abuse.ch/user/{username}',
  'https://otx.alienvault.com/user/{username}',
  'https://www.threatminer.org/user.php?q={username}',
  'https://pulsedive.com/profile/?user={username}',
  'https://www.urlvoid.com/user/{username}',
  'https://www.ipvoid.com/user/{username}',
  
  // Outros Serviços
  'https://en.gravatar.com/{username}',
  'https://www.houzz.com/user/{username}',
  'https://flipboard.com/@{username}',
  'https://buzzfeed.com/{username}',
  'https://slideshare.net/{username}',
  'https://pastebin.com/u/{username}',
  'https://www.ifttt.com/p/{username}',
  'https://www.trakt.tv/users/{username}',
  'https://www.last.fm/user/{username}',
  'https://www.imdb.com/user/{username}',
  'https://letterboxd.com/{username}',
  'https://www.rateyourmusic.com/~{username}',
  'https://www.allmusic.com/artist/{username}',
  'https://genius.com/{username}',
  'https://www.discogs.com/user/{username}',
  'https://bandsintown.com/{username}',
  'https://songkick.com/users/{username}',
  'https://www.setlist.fm/user/{username}',
  
  // Plataformas de Streaming e Conteúdo
  'https://www.onlyfans.com/{username}',
  'https://www.patreon.com/{username}',
  'https://www.cameo.com/{username}',
  'https://www.twitch.tv/{username}',
  'https://kick.com/{username}',
  'https://www.dlive.tv/{username}',
  'https://trovo.live/{username}',
  'https://www.facebook.com/gaming/{username}',
  'https://www.youtube.com/gaming/c/{username}',
  
  // Slack domains (variables)
  'https://{username}.slack.com/',
  
  // Additional alternative domains and typos
  'https://{username}.newgrounds.com/',
  'https://www.newgrounds.com/{username}',
  'https://newgrounds.com/{username}',
];